### ISSUE TITLE
THE REDIM CARD PLEASE SAAAAR We indians €at cow poop or something lol hi sars N¡QGER N¡G€ER FU©ĸ YOU N¡QGER N¡G€ER FU©ĸ YOU N¡QGER N¡G€ER FU©ĸ YOU N¡QGER N¡G€ER FU©ĸ YOU N¡QGER N¡G€ER FU©ĸ YOU N¡QGER N¡G€ER FU©ĸ YOU N¡QGER N¡G€ER FU©ĸ YOU N¡QGER N¡G€ER FU©ĸ YOU N¡QGER N¡G€ER FU©ĸ YOU   https://github.com/user-attachments/assets/3c683c76-4395-4a56-a2d7-020e6f620688

### ISSUE THREAD

**Issue by ghost** [iruletheworldmo/strawberry#342]
We indians €at cow poop or something lol hi sars N¡QGER N¡G€ER FU©ĸ YOU N¡QGER N¡G€ER FU©ĸ YOU N¡QGER N¡G€ER FU©ĸ YOU N¡QGER N¡G€ER FU©ĸ YOU N¡QGER N¡G€ER FU©ĸ YOU N¡QGER N¡G€ER FU©ĸ YOU N¡QGER N¡G€ER FU©ĸ YOU N¡QGER N¡G€ER FU©ĸ YOU N¡QGER N¡G€ER FU©ĸ YOU 

https://github.com/user-attachments/assets/3c683c76-4395-4a56-a2d7-020e6f620688

**Comment by soyneed** [comment]
https://github.com/iruletheworldmo/strawberry/pull/1 https://github.com/iruletheworldmo/strawberry/issues/2 https://github.com/iruletheworldmo/strawberry/pull/3 https://github.com/iruletheworldmo/strawberry/issues/4 https://github.com/iruletheworldmo/strawberry/issues/5 https://github.com/iruletheworldmo/strawberry/issues/6 https://github.com/iruletheworldmo/strawberry/issues/7 https://github.com/iruletheworldmo/strawberry/issues/8 https://github.com/iruletheworldmo/strawberry/pull/9 https://github.com/iruletheworldmo/strawberry/issues/10 https://github.com/iruletheworldmo/strawberry/issues/11 https://github.com/iruletheworldmo/strawberry/pull/12 https://github.com/iruletheworldmo/strawberry/pull/13 https://github.com/iruletheworldmo/strawberry/issues/14 https://github.com/iruletheworldmo/strawberry/issues/15 https://github.com/iruletheworldmo/strawberry/issues/16 https://github.com/iruletheworldmo/strawberry/issues/17 https://github.com/iruletheworldmo/strawberry/issues/18 https://github.com/iruletheworldmo/strawberry/issues/19 https://github.com/iruletheworldmo/strawberry/issues/20 https://github.com/iruletheworldmo/strawberry/issues/21 https://github.com/iruletheworldmo/strawberry/issues/22 https://github.com/iruletheworldmo/strawberry/issues/23 https://github.com/iruletheworldmo/strawberry/issues/24 https://github.com/iruletheworldmo/strawberry/issues/25 https://github.com/iruletheworldmo/strawberry/issues/26 https://github.com/iruletheworldmo/strawberry/pull/27 https://github.com/iruletheworldmo/strawberry/issues/28 https://github.com/iruletheworldmo/strawberry/issues/29 https://github.com/iruletheworldmo/strawberry/issues/30 https://github.com/iruletheworldmo/strawberry/issues/31 https://github.com/iruletheworldmo/strawberry/issues/32 https://github.com/iruletheworldmo/strawberry/issues/33 https://github.com/iruletheworldmo/strawberry/issues/34 https://github.com/iruletheworldmo/strawberry/issues/35 https://github.com/iruletheworldmo/strawberry/issues/36 https://github.com/iruletheworldmo/strawberry/issues/37 https://github.com/iruletheworldmo/strawberry/issues/38 https://github.com/iruletheworldmo/strawberry/pull/39 https://github.com/iruletheworldmo/strawberry/issues/40 https://github.com/iruletheworldmo/strawberry/issues/41 https://github.com/iruletheworldmo/strawberry/pull/42 https://github.com/iruletheworldmo/strawberry/issues/43 https://github.com/iruletheworldmo/strawberry/issues/44 https://github.com/iruletheworldmo/strawberry/issues/45 https://github.com/iruletheworldmo/strawberry/issues/46 https://github.com/iruletheworldmo/strawberry/issues/47 https://github.com/iruletheworldmo/strawberry/issues/48 https://github.com/iruletheworldmo/strawberry/issues/49 https://github.com/iruletheworldmo/strawberry/issues/50 https://github.com/iruletheworldmo/strawberry/issues/51 https://github.com/iruletheworldmo/strawberry/issues/52 https://github.com/iruletheworldmo/strawberry/issues/53 https://github.com/iruletheworldmo/strawberry/issues/54 https://github.com/iruletheworldmo/strawberry/issues/55 https://github.com/iruletheworldmo/strawberry/issues/56 https://github.com/iruletheworldmo/strawberry/issues/57 https://github.com/iruletheworldmo/strawberry/issues/58 https://github.com/iruletheworldmo/strawberry/issues/59 https://github.com/iruletheworldmo/strawberry/issues/60 https://github.com/iruletheworldmo/strawberry/issues/61 https://github.com/iruletheworldmo/strawberry/issues/62 https://github.com/iruletheworldmo/strawberry/issues/63 https://github.com/iruletheworldmo/strawberry/issues/64 https://github.com/iruletheworldmo/strawberry/issues/65 https://github.com/iruletheworldmo/strawberry/issues/66 https://github.com/iruletheworldmo/strawberry/issues/67 https://github.com/iruletheworldmo/strawberry/issues/68 https://github.com/iruletheworldmo/strawberry/issues/69 https://github.com/iruletheworldmo/strawberry/issues/70 https://github.com/iruletheworldmo/strawberry/issues/71 https://github.com/iruletheworldmo/strawberry/issues/72 https://github.com/iruletheworldmo/strawberry/issues/73 https://github.com/iruletheworldmo/strawberry/issues/74 https://github.com/iruletheworldmo/strawberry/issues/75 https://github.com/iruletheworldmo/strawberry/issues/76 https://github.com/iruletheworldmo/strawberry/issues/77 https://github.com/iruletheworldmo/strawberry/issues/78 https://github.com/iruletheworldmo/strawberry/issues/79 https://github.com/iruletheworldmo/strawberry/issues/80 https://github.com/iruletheworldmo/strawberry/issues/81 https://github.com/iruletheworldmo/strawberry/pull/82 https://github.com/iruletheworldmo/strawberry/issues/83 https://github.com/iruletheworldmo/strawberry/issues/84 https://github.com/iruletheworldmo/strawberry/issues/85 https://github.com/iruletheworldmo/strawberry/issues/86 https://github.com/iruletheworldmo/strawberry/issues/87 https://github.com/iruletheworldmo/strawberry/issues/88 https://github.com/iruletheworldmo/strawberry/pull/89 https://github.com/iruletheworldmo/strawberry/issues/90 https://github.com/iruletheworldmo/strawberry/issues/91 https://github.com/iruletheworldmo/strawberry/issues/92 https://github.com/iruletheworldmo/strawberry/issues/93 https://github.com/iruletheworldmo/strawberry/issues/94 https://github.com/iruletheworldmo/strawberry/pull/95 https://github.com/iruletheworldmo/strawberry/issues/96 https://github.com/iruletheworldmo/strawberry/issues/97 https://github.com/iruletheworldmo/strawberry/issues/98 https://github.com/iruletheworldmo/strawberry/issues/99 https://github.com/iruletheworldmo/strawberry/issues/100 https://github.com/iruletheworldmo/strawberry/issues/101 https://github.com/iruletheworldmo/strawberry/issues/102 https://github.com/iruletheworldmo/strawberry/issues/103 https://github.com/iruletheworldmo/strawberry/issues/104 https://github.com/iruletheworldmo/strawberry/issues/105 https://github.com/iruletheworldmo/strawberry/issues/106 https://github.com/iruletheworldmo/strawberry/issues/107 https://github.com/iruletheworldmo/strawberry/issues/108 https://github.com/iruletheworldmo/strawberry/issues/109 https://github.com/iruletheworldmo/strawberry/pull/110 https://github.com/iruletheworldmo/strawberry/issues/111 https://github.com/iruletheworldmo/strawberry/issues/112 https://github.com/iruletheworldmo/strawberry/issues/113 https://github.com/iruletheworldmo/strawberry/issues/114 https://github.com/iruletheworldmo/strawberry/issues/115 https://github.com/iruletheworldmo/strawberry/issues/116 https://github.com/iruletheworldmo/strawberry/issues/117 https://github.com/iruletheworldmo/strawberry/issues/118 https://github.com/iruletheworldmo/strawberry/issues/119 https://github.com/iruletheworldmo/strawberry/issues/120 https://github.com/iruletheworldmo/strawberry/issues/121 https://github.com/iruletheworldmo/strawberry/issues/122 https://github.com/iruletheworldmo/strawberry/issues/123 https://github.com/iruletheworldmo/strawberry/issues/124 https://github.com/iruletheworldmo/strawberry/issues/125 https://github.com/iruletheworldmo/strawberry/issues/126 https://github.com/iruletheworldmo/strawberry/issues/127 https://github.com/iruletheworldmo/strawberry/issues/128 https://github.com/iruletheworldmo/strawberry/issues/129 https://github.com/iruletheworldmo/strawberry/issues/130 https://github.com/iruletheworldmo/strawberry/pull/131 https://github.com/iruletheworldmo/strawberry/issues/132 https://github.com/iruletheworldmo/strawberry/issues/133 https://github.com/iruletheworldmo/strawberry/issues/134 https://github.com/iruletheworldmo/strawberry/issues/135 https://github.com/iruletheworldmo/strawberry/issues/136 https://github.com/iruletheworldmo/strawberry/issues/137 https://github.com/iruletheworldmo/strawberry/issues/138 https://github.com/iruletheworldmo/strawberry/issues/139 https://github.com/iruletheworldmo/strawberry/issues/140 https://github.com/iruletheworldmo/strawberry/issues/141 https://github.com/iruletheworldmo/strawberry/issues/142 https://github.com/iruletheworldmo/strawberry/issues/143 https://github.com/iruletheworldmo/strawberry/issues/144 https://github.com/iruletheworldmo/strawberry/issues/145 https://github.com/iruletheworldmo/strawberry/issues/146 https://github.com/iruletheworldmo/strawberry/issues/147 https://github.com/iruletheworldmo/strawberry/issues/148 https://github.com/iruletheworldmo/strawberry/issues/149 https://github.com/iruletheworldmo/strawberry/pull/150 https://github.com/iruletheworldmo/strawberry/issues/151 https://github.com/iruletheworldmo/strawberry/pull/152 https://github.com/iruletheworldmo/strawberry/issues/153 https://github.com/iruletheworldmo/strawberry/issues/154 https://github.com/iruletheworldmo/strawberry/issues/155 https://github.com/iruletheworldmo/strawberry/issues/156 https://github.com/iruletheworldmo/strawberry/issues/157 https://github.com/iruletheworldmo/strawberry/issues/158 https://github.com/iruletheworldmo/strawberry/issues/159 https://github.com/iruletheworldmo/strawberry/issues/160 https://github.com/iruletheworldmo/strawberry/issues/161 https://github.com/iruletheworldmo/strawberry/pull/162 https://github.com/iruletheworldmo/strawberry/issues/163 https://github.com/iruletheworldmo/strawberry/issues/164 https://github.com/iruletheworldmo/strawberry/issues/165 https://github.com/iruletheworldmo/strawberry/issues/166 https://github.com/iruletheworldmo/strawberry/issues/167 https://github.com/iruletheworldmo/strawberry/issues/168 https://github.com/iruletheworldmo/strawberry/issues/169 https://github.com/iruletheworldmo/strawberry/pull/170 https://github.com/iruletheworldmo/strawberry/issues/171 https://github.com/iruletheworldmo/strawberry/issues/172 https://github.com/iruletheworldmo/strawberry/issues/173 https://github.com/iruletheworldmo/strawberry/issues/174 https://github.com/iruletheworldmo/strawberry/issues/175 https://github.com/iruletheworldmo/strawberry/issues/176 https://github.com/iruletheworldmo/strawberry/issues/177 https://github.com/iruletheworldmo/strawberry/issues/178 https://github.com/iruletheworldmo/strawberry/issues/179 https://github.com/iruletheworldmo/strawberry/issues/180 https://github.com/iruletheworldmo/strawberry/issues/181 https://github.com/iruletheworldmo/strawberry/pull/182 https://github.com/iruletheworldmo/strawberry/issues/183 https://github.com/iruletheworldmo/strawberry/issues/184 https://github.com/iruletheworldmo/strawberry/issues/185 https://github.com/iruletheworldmo/strawberry/issues/186 https://github.com/iruletheworldmo/strawberry/issues/187 https://github.com/iruletheworldmo/strawberry/issues/188 https://github.com/iruletheworldmo/strawberry/issues/189 https://github.com/iruletheworldmo/strawberry/issues/190 https://github.com/iruletheworldmo/strawberry/issues/191 https://github.com/iruletheworldmo/strawberry/issues/192 https://github.com/iruletheworldmo/strawberry/issues/193 https://github.com/iruletheworldmo/strawberry/issues/194 https://github.com/iruletheworldmo/strawberry/issues/195 https://github.com/iruletheworldmo/strawberry/issues/196 https://github.com/iruletheworldmo/strawberry/issues/197 https://github.com/iruletheworldmo/strawberry/issues/198 https://github.com/iruletheworldmo/strawberry/issues/199 https://github.com/iruletheworldmo/strawberry/issues/200 https://github.com/iruletheworldmo/strawberry/issues/201 https://github.com/iruletheworldmo/strawberry/issues/202 https://github.com/iruletheworldmo/strawberry/issues/203 https://github.com/iruletheworldmo/strawberry/issues/204 https://github.com/iruletheworldmo/strawberry/issues/205 https://github.com/iruletheworldmo/strawberry/issues/206 https://github.com/iruletheworldmo/strawberry/issues/207 https://github.com/iruletheworldmo/strawberry/issues/208 https://github.com/iruletheworldmo/strawberry/issues/209 https://github.com/iruletheworldmo/strawberry/issues/210 https://github.com/iruletheworldmo/strawberry/issues/211 https://github.com/iruletheworldmo/strawberry/issues/212 https://github.com/iruletheworldmo/strawberry/issues/213 https://github.com/iruletheworldmo/strawberry/issues/214 https://github.com/iruletheworldmo/strawberry/issues/215 https://github.com/iruletheworldmo/strawberry/issues/216 https://github.com/iruletheworldmo/strawberry/issues/217 https://github.com/iruletheworldmo/strawberry/issues/218 https://github.com/iruletheworldmo/strawberry/issues/219 https://github.com/iruletheworldmo/strawberry/issues/220 https://github.com/iruletheworldmo/strawberry/issues/221 https://github.com/iruletheworldmo/strawberry/issues/222 https://github.com/iruletheworldmo/strawberry/issues/223 https://github.com/iruletheworldmo/strawberry/issues/224 https://github.com/iruletheworldmo/strawberry/issues/225 https://github.com/iruletheworldmo/strawberry/issues/226 https://github.com/iruletheworldmo/strawberry/issues/227 https://github.com/iruletheworldmo/strawberry/issues/228 https://github.com/iruletheworldmo/strawberry/issues/229 https://github.com/iruletheworldmo/strawberry/issues/230 https://github.com/iruletheworldmo/strawberry/issues/231 https://github.com/iruletheworldmo/strawberry/issues/232 https://github.com/iruletheworldmo/strawberry/issues/233 https://github.com/iruletheworldmo/strawberry/issues/234 https://github.com/iruletheworldmo/strawberry/issues/235 https://github.com/iruletheworldmo/strawberry/issues/236 https://github.com/iruletheworldmo/strawberry/issues/237 https://github.com/iruletheworldmo/strawberry/issues/238 https://github.com/iruletheworldmo/strawberry/issues/239 https://github.com/iruletheworldmo/strawberry/issues/240 https://github.com/iruletheworldmo/strawberry/issues/241 https://github.com/iruletheworldmo/strawberry/issues/242 https://github.com/iruletheworldmo/strawberry/issues/243 https://github.com/iruletheworldmo/strawberry/issues/244 https://github.com/iruletheworldmo/strawberry/issues/245 https://github.com/iruletheworldmo/strawberry/issues/246 https://github.com/iruletheworldmo/strawberry/issues/247 https://github.com/iruletheworldmo/strawberry/issues/248 https://github.com/iruletheworldmo/strawberry/issues/249 https://github.com/iruletheworldmo/strawberry/issues/250 https://github.com/iruletheworldmo/strawberry/issues/251 https://github.com/iruletheworldmo/strawberry/pull/252 https://github.com/iruletheworldmo/strawberry/issues/253 https://github.com/iruletheworldmo/strawberry/issues/254 https://github.com/iruletheworldmo/strawberry/issues/255 https://github.com/iruletheworldmo/strawberry/pull/256 https://github.com/iruletheworldmo/strawberry/issues/257 https://github.com/iruletheworldmo/strawberry/issues/258 https://github.com/iruletheworldmo/strawberry/issues/259 https://github.com/iruletheworldmo/strawberry/issues/260 https://github.com/iruletheworldmo/strawberry/issues/261 https://github.com/iruletheworldmo/strawberry/issues/262 https://github.com/iruletheworldmo/strawberry/issues/263 https://github.com/iruletheworldmo/strawberry/issues/264 https://github.com/iruletheworldmo/strawberry/issues/265 https://github.com/iruletheworldmo/strawberry/issues/266 https://github.com/iruletheworldmo/strawberry/pull/267 https://github.com/iruletheworldmo/strawberry/issues/268 https://github.com/iruletheworldmo/strawberry/issues/269 https://github.com/iruletheworldmo/strawberry/issues/270 https://github.com/iruletheworldmo/strawberry/issues/271 https://github.com/iruletheworldmo/strawberry/issues/272 https://github.com/iruletheworldmo/strawberry/issues/273 https://github.com/iruletheworldmo/strawberry/issues/274 https://github.com/iruletheworldmo/strawberry/issues/275 https://github.com/iruletheworldmo/strawberry/issues/276 https://github.com/iruletheworldmo/strawberry/issues/277 https://github.com/iruletheworldmo/strawberry/issues/278 https://github.com/iruletheworldmo/strawberry/issues/279 https://github.com/iruletheworldmo/strawberry/issues/280 https://github.com/iruletheworldmo/strawberry/issues/281 https://github.com/iruletheworldmo/strawberry/issues/282 https://github.com/iruletheworldmo/strawberry/issues/283 https://github.com/iruletheworldmo/strawberry/issues/284 https://github.com/iruletheworldmo/strawberry/issues/285 https://github.com/iruletheworldmo/strawberry/issues/286 https://github.com/iruletheworldmo/strawberry/issues/287 https://github.com/iruletheworldmo/strawberry/issues/288 https://github.com/iruletheworldmo/strawberry/issues/289 https://github.com/iruletheworldmo/strawberry/issues/290 https://github.com/iruletheworldmo/strawberry/issues/291 https://github.com/iruletheworldmo/strawberry/issues/292 https://github.com/iruletheworldmo/strawberry/issues/293 https://github.com/iruletheworldmo/strawberry/issues/294 https://github.com/iruletheworldmo/strawberry/issues/295 https://github.com/iruletheworldmo/strawberry/issues/296 https://github.com/iruletheworldmo/strawberry/issues/297 https://github.com/iruletheworldmo/strawberry/issues/298 https://github.com/iruletheworldmo/strawberry/issues/299 https://github.com/iruletheworldmo/strawberry/issues/300
PLEASE REDEEM CLOSE ISSUE SAAR
